# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gas_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 374)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comunidadCB = QtWidgets.QComboBox(self.centralwidget)
        self.comunidadCB.setGeometry(QtCore.QRect(10, 10, 161, 26))
        self.comunidadCB.setObjectName("comunidadCB")
        self.provinciaCB = QtWidgets.QComboBox(self.centralwidget)
        self.provinciaCB.setEnabled(True)
        self.provinciaCB.setGeometry(QtCore.QRect(180, 10, 161, 26))
        self.provinciaCB.setObjectName("provinciaCB")
        self.municipioCB = QtWidgets.QComboBox(self.centralwidget)
        self.municipioCB.setEnabled(True)
        self.municipioCB.setGeometry(QtCore.QRect(350, 10, 161, 26))
        self.municipioCB.setObjectName("municipioCB")
        self.salirBtn = QtWidgets.QPushButton(self.centralwidget)
        self.salirBtn.setGeometry(QtCore.QRect(410, 300, 113, 32))
        self.salirBtn.setObjectName("salirBtn")
        self.direccionCB = QtWidgets.QComboBox(self.centralwidget)
        self.direccionCB.setEnabled(True)
        self.direccionCB.setGeometry(QtCore.QRect(10, 40, 501, 26))
        self.direccionCB.setObjectName("direccionCB")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 221, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sp95LCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.sp95LCD.setSmallDecimalPoint(True)
        self.sp95LCD.setDigitCount(4)
        self.sp95LCD.setObjectName("sp95LCD")
        self.gridLayout.addWidget(self.sp95LCD, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.sp98LCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.sp98LCD.setEnabled(True)
        self.sp98LCD.setSmallDecimalPoint(True)
        self.sp98LCD.setDigitCount(4)
        self.sp98LCD.setProperty("value", 0.0)
        self.sp98LCD.setProperty("intValue", 0)
        self.sp98LCD.setObjectName("sp98LCD")
        self.gridLayout.addWidget(self.sp98LCD, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(280, 70, 221, 111))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.gasoleoBLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.gasoleoBLCD.setEnabled(True)
        self.gasoleoBLCD.setSmallDecimalPoint(True)
        self.gasoleoBLCD.setDigitCount(4)
        self.gasoleoBLCD.setProperty("value", 0.0)
        self.gasoleoBLCD.setProperty("intValue", 0)
        self.gasoleoBLCD.setObjectName("gasoleoBLCD")
        self.gridLayout_2.addWidget(self.gasoleoBLCD, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gasoleoALCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.gasoleoALCD.setSmallDecimalPoint(True)
        self.gasoleoALCD.setDigitCount(4)
        self.gasoleoALCD.setObjectName("gasoleoALCD")
        self.gridLayout_2.addWidget(self.gasoleoALCD, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.gasoleoPremiumLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.gasoleoPremiumLCD.setEnabled(True)
        self.gasoleoPremiumLCD.setSmallDecimalPoint(True)
        self.gasoleoPremiumLCD.setDigitCount(4)
        self.gasoleoPremiumLCD.setProperty("value", 0.0)
        self.gasoleoPremiumLCD.setProperty("intValue", 0)
        self.gasoleoPremiumLCD.setObjectName("gasoleoPremiumLCD")
        self.gridLayout_2.addWidget(self.gasoleoPremiumLCD, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Buscador de gasolineras"))
        self.salirBtn.setText(_translate("MainWindow", "SALIR"))
        self.label.setText(_translate("MainWindow", "Sin Plomo 95"))
        self.label_2.setText(_translate("MainWindow", "Sin Plomo 98"))
        self.label_4.setText(_translate("MainWindow", "Gasoleo B"))
        self.label_3.setText(_translate("MainWindow", "Gasoleo A"))
        self.label_5.setText(_translate("MainWindow", "Gasoleo Premium"))

